# a parameter yaml to get the relation of the tf
# 以所有车都有的关节action作为坐标发布点，更加具有通用性
tfRobot1:
  frame_id: /robot1/odom
  child_frame_id: robot1/base_footprint
tfRobot2:
  frame_id: /robot2/odom
  child_frame_id: robot2/base_link
tfRobot3:
  frame_id: /robot3/odom
  child_frame_id: robot3/base_footprint
tfRobot4:
  frame_id: /robot4/odom
  child_frame_id: robot4/base_link